name             'role-win-base-nativex'
maintainer       'NativeX'
maintainer_email 'adrian.herrera@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-win-base-nativex'
version          '0.2.0'

depends 'ohai-nativex'
depends 'aws'
depends 'windows'
depends 'ad-nativex'
depends 'dnsupdate-nativex'
depends 'autopatch-nativex'
depends 'chef-client'
