name             'role-privoxy-nativex'
maintainer       'NativeX'
maintainer_email 'adrian.herrera@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-privoxy-nativex'
version          '0.3.0'

depends 'role-base-nativex', '=0.2.0'
depends 'privoxy-nativex', '=0.1.0'
depends 'iptables-nativex', '=0.1.0'
