---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-13.10
  - name: debian-7.4
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[limits::default]
    attributes:
