name             'role-datascience-simplyadrian'
maintainer       'simplyadrian'
maintainer_email 'simplyadrian@gmail.com'
license          'All rights reserved'
description      'Installs/Configures role-datascience-simplyadrian'
version          '2.1.0'

depends 'role-base-simplyadrian'
depends 'cifs-simplyadrian'
depends 'git'
depends 'blockdevice-simplyadrian'
depends 'mkdirs-simplyadrian'
depends 'nodejs'
depends 'python'
depends 'python-simplyadrian'
depends 'r'
depends 'r-simplyadrian'
depends 'rabbitmq'
depends 'tuned-simplyadrian'
