name             'role-win-base-simplyadrian'
maintainer       'simplyadrian'
maintainer_email 'simplyadrian@gmail.com'
license          'All rights reserved'
description      'Installs/Configures role-win-base-simplyadrian'
version          '1.0.0'

depends 'ohai-simplyadrian'
depends 'aws'
depends 'timezone-simplyadrian'
depends 'windows'
depends 'ad-simplyadrian'
depends 'autopatch-simplyadrian'
depends 'chef-client'
depends 'chef-sugar'
