name             'role-theano-nativex'
maintainer       'NativeX'
maintainer_email 'adrian.herrera@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-theano-nativex'
version          '0.1.0'

depends 'ohai-nativex'
depends 'aws'
depends 'xml'
depends 'users'
depends 'sudo'
depends 'apt'
depends 'vim'
depends 'nano'
depends 'bash-completion'
depends 'dstat'
depends 'ephemeral_lvm-nativex'
depends 'blockdevice-nativex'
depends 'dnsupdate-nativex'
depends 'hostname-nativex'
depends 'snmp'
depends 'ntp'
depends 'motd'
depends 'chef-client'
