name             'role-theano-nativex'
maintainer       'NativeX'
maintainer_email 'adrian.herrera@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-theano-nativex'
version          '0.1.0'

depends 'ohai-nativex', '=0.1.1'
depends 'aws', '=2.5.0'
depends 'xml', '=1.2.6'
depends 'users', '=1.7.0'
depends 'sudo', '=2.6.0'
depends 'apt', '=2.5.0'
depends 'vim', '=1.1.2'
depends 'nano', '=1.0.0'
depends 'bash-completion', '=0.1.0'
depends 'dstat', '=0.1.1'
depends 'ephemeral_lvm-nativex', '=0.1.0'
depends 'blockdevice-nativex', '=0.1.1'
depends 'dnsupdate-nativex', '=0.1.0'
depends 'hostname-nativex', '=0.1.0'
depends 'iptables', '=0.13.2'
depends 'snmp', '=3.0.1'
depends 'ntp', '=1.6.4'
depends 'motd', '=0.5.0'
depends 'chef-client', '=3.8.0'