name             'role-base-simplyadrian'
maintainer       'simplyadrian'
maintainer_email 'simplyadrian@gmail.com'
license          'All rights reserved'
description      'Installs/Configures role-base-simplyadrian'
version          '1.3.0'

depends 'ohai-simplyadrian'
depends 'chef-sugar'
depends 'autofs-simplyadrian'
depends 'autopatch-simplyadrian'
depends 'auto-patch'
depends 'aws'
depends 'vim'
depends 'nano'
depends 'bash-completion'
depends 'dstat'
depends 'numad-simplyadrian'
depends 'tuned-simplyadrian'
depends 'nfs'
depends 'ephemeral_lvm-simplyadrian'
depends 'snmp'
depends 'sshd'
depends 'sudo'
depends 'hostname-simplyadrian'
depends 'yum-simplyadrian'
depends 'yum-epel'
depends 'spacewalk-simplyadrian'
depends 'ad-simplyadrian'
depends 'ntp'
depends 'timezone-simplyadrian'
depends 'motd'
depends 'chef-client'
