source "https://supermarket.getchef.com"

metadata

cookbook 'spacewalk-nativex', '0.3.0', git: 'git@github.com:nativex/cookbook-spacewalk-nativex.git'
cookbook 'chef-client', '3.8.0'
cookbook 'chef_handler', '1.1.6'
cookbook 'cron', '1.6.1'
cookbook 'motd', '0.5.0'
cookbook 'windows', '1.34.6'