source "https://supermarket.getchef.com"

metadata

cookbook 'spacewalk-nativex', '0.5.0', git: 'git@github.com:nativex/cookbook-spacewalk-nativex.git', ref: 'a94920c2949d6bda5641728d40f2e6eee1bae29b'
cookbook 'chef-client', '3.8.0'
cookbook 'chef_handler', '1.1.6'
cookbook 'cron', '1.6.1'
cookbook 'motd', '0.5.0'
cookbook 'windows', '1.34.6'
