source "https://supermarket.getchef.com"

metadata

cookbook 'autopatch-nativex', '1.1.0', git: 'git@github.com:nativex/cookbook-autopatch-nativex.git', ref: '0f78b57da9839d9bb792a3ab71233658e8b4549d'
cookbook 'spacewalk-nativex', '0.5.1', git: 'git@github.com:nativex/cookbook-spacewalk-nativex.git'
cookbook 'auto-patch', '0.1.9'
cookbook 'chef-client', '3.8.0'
cookbook 'chef_handler', '1.1.6'
cookbook 'cron', '1.6.1'
cookbook 'motd', '0.5.0'
cookbook 'windows', '1.34.6'
