name             'role-spacewalk-server-nativex'
maintainer       'NativeX'
maintainer_email 'adrian.herrera@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-spacewalk-server-nativex'
version          '0.2.0'

depends 'autopatch-nativex'
depends 'motd'
depends 'spacewalk-nativex'
depends 'chef-client'
