name             'role-nas-simplyadrian'
maintainer       'simplyadrian'
maintainer_email 'simplyadrian@gmail.com'
license          'All rights reserved'
description      'Installs/Configures role-nas-simplyadrian'
version          '0.2.0'

depends 'role-base-simplyadrian'
depends 'tuned-simplyadrian'
depends 'nfs'
depends 'blockdevice-simplyadrian'
depends 'nfs-simplyadrian'
