name             'role-nas-nativex'
maintainer       'NativeX'
maintainer_email 'adrian.herrera@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-nas-nativex'
version          '0.2.0'

depends 'role-base-nativex'
depends 'tuned-nativex'
depends 'nfs'
depends 'blockdevice-nativex'
depends 'nfs-nativex'
