name             'role-nas-nativex'
maintainer       'NativeX'
maintainer_email 'adrian.herrera@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-nas-nativex'
version          '0.1.0'

depends 'role-base-nativex', '0.1.0'
depends 'tuned-nativex', '0.1.0'
depends 'nfs', '2.0.0'
depends 'blockdevice-nativex', '0.1.1'
depends 'nfs-nativex', '0.1.0'