source "https://supermarket.getchef.com"

metadata

cookbook 'autopatch-nativex', '0.1.0', git: 'git@github.com:nativex/cookbook-autopatch-nativex.git', ref: 'e3d0d0c575ff7d95a77d5d6081aab74632b73e79' 
cookbook 'chef-client', '3.8.0'
cookbook 'chef_handler', '1.1.6'
cookbook 'windows', '1.37.0', git: 'git@github.com:nativex/windows.git', ref: '42013d8ecd323e20d16ab580c41e4a35b5ed627d'
