name             'role-base-nativex'
maintainer       'NativeX'
maintainer_email 'adrian.herrera@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-base-nativex'
version          '1.3.0'

depends 'ohai-nativex'
depends 'chef-sugar'
depends 'autofs-nativex'
depends 'autopatch-nativex'
depends 'auto-patch'
depends 'aws'
depends 'vim'
depends 'nano'
depends 'bash-completion'
depends 'dstat'
depends 'numad-nativex'
depends 'tuned-nativex'
depends 'nfs'
depends 'ephemeral_lvm-nativex'
depends 'snmp'
depends 'sshd'
depends 'sudo'
depends 'hostname-nativex'
depends 'yum-nativex'
depends 'yum-epel'
depends 'spacewalk-nativex'
depends 'ad-nativex'
depends 'ntp'
depends 'timezone-nativex'
depends 'motd'
depends 'chef-client'
