name             'role-datascience-nativex'
maintainer       'NativeX'
maintainer_email 'adrian.herrera@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-datascience-nativex'
version          '0.1.0'

depends 'role-base-nativex', '0.1.0'
depends 'cifs-nativex', '0.1.0'
depends 'git', '4.0.2'
depends 'blockdevice-nativex', '0.1.1'
depends 'iptables-nativex', '0.1.0'
depends 'nodejs', '2.2.0'
depends 'python', '1.4.6'
depends 'python-nativex', '0.1.0'
depends 'r', '0.3.0'
depends 'r-nativex', '0.1.1'
depends 'rabbitmq', '3.2.2'
depends 'tuned-nativex', '0.1.0'