name             'role-datascience-nativex'
maintainer       'NativeX'
maintainer_email 'adrian.herrera@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-datascience-nativex'
version          '2.1.0'

depends 'role-base-nativex'
depends 'cifs-nativex'
depends 'git'
depends 'blockdevice-nativex'
depends 'mkdirs-nativex'
depends 'nodejs'
depends 'python'
depends 'python-nativex'
depends 'r'
depends 'r-nativex'
depends 'rabbitmq'
depends 'tuned-nativex'
