name             'role-onpremise-base-nativex'
maintainer       'NativeX'
maintainer_email 'derek.bromenshenkel@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-onpremise-base-nativex'
long_description 'Installs/Configures role-onpremise-base-nativex'
version          '1.0.0'

depends 'ad-nativex'
depends 'autofs-nativex'
depends 'autopatch-nativex'
depends 'chef-client'
depends 'chef-sugar'
depends 'sshd'
depends 'sudo'
