name             'role-onpremise-base-nativex'
maintainer       'NativeX'
maintainer_email 'derek.bromenshenkel@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-onpremise-base-nativex'
long_description 'Installs/Configures role-onpremise-base-nativex'
version          '0.1.0'

depends 'autopatch-nativex'
depends 'chef-client'
