name             'role-win-onpremise-base-simplyadrian'
maintainer       'simplyadrian'
maintainer_email 'simplyadrian@gmail.com'
license          'All rights reserved'
description      'Installs/Configures role-win-onpremise-base-simplyadrian'
long_description 'Installs/Configures role-win-onpremise-base-simplyadrian'
version          '1.0.0'

depends 'autopatch-simplyadrian'
depends 'chef-client'
