name             'role-dse-nativex'
maintainer       'NativeX'
maintainer_email 'adrian.herrera@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-dse-nativex'
version          '1.2.0'

depends 'role-base-nativex'
depends 'tuned-nativex'
depends 'dse-nativex'
