source "https://supermarket.getchef.com"

metadata

cookbook 'autofs-nativex', '0.1.0', git: 'git@github.com:nativex/cookbook-autofs-nativex.git', ref: 'f4b878de887d0f953552d6d2083c7e7fd3a91711'
cookbook 'ohai-nativex', '0.1.1', git: 'git@github.com:nativex/cookbook-ohai-nativex.git'
cookbook 'chef-sugar', '2.5.0'
cookbook 'line', '0.6.0'
cookbook 'ohai', '2.0.1'
cookbook 'resource', '~> 0.2.1'
