name             'role-linux-domain-member-nativex'
maintainer       'NativeX'
maintainer_email 'adrian.herrera@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-linux-domain-member-nativex'
version          '0.1.0'

depends 'chef-sugar'
depends 'line'
depends 'ohai-nativex'
depends 'resource'
