name             'role-domain-controller-nativex'
maintainer       'NativeX'
maintainer_email 'adrian.herrera@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-domain-controller-nativex'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'aws'
depends 'windows'
depends 'ad-nativex::joindomain'
depends 'ad-nativex::installdomaincontroller'
depends 'dnsupdate-nativex::addprv'
depends 'chef-client::delete_validation'
depends 'chef-client'