name             'role-domain-controller-nativex'
maintainer       'NativeX'
maintainer_email 'adrian.herrera@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-domain-controller-nativex'
version          '0.3.0'

depends 'ad-nativex'
depends 'autopatch-nativex'
depends 'aws'
depends 'timezone-nativex'
depends 'chef-client'
depends 'chef-sugar'
depends 'windows'
