name             'role-onpremise-base-simplyadrian'
maintainer       'simplyadrian'
maintainer_email 'simplyadrian@gmail.com'
license          'All rights reserved'
description      'Installs/Configures role-onpremise-base-simplyadrian'
long_description 'Installs/Configures role-onpremise-base-simplyadrian'
version          '1.0.0'

depends 'ad-simplyadrian'
depends 'autofs-simplyadrian'
depends 'autopatch-simplyadrian'
depends 'autofs-simplyadrian'
depends 'chef-client'
depends 'chef-sugar'
depends 'ntp'
depends 'sshd'
depends 'sudo'
