name             'role-nat-nativex'
maintainer       'NativeX'
maintainer_email 'adrian.herrera@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-nat-nativex'
version          '0.3.0'

depends 'autopatch-nativex'
depends 'ohai-nativex'
depends 'aws'
depends 'vim'
depends 'nano'
depends 'bash-completion'
depends 'dstat'
depends 'numad-nativex'
depends 'tuned-nativex'
depends 'nfs'
depends 'ephemeral_lvm-nativex'
depends 'snmp'
depends 'dnsupdate-nativex'
depends 'hostname-nativex'
depends 'yum-nativex'
depends 'spacewalk-nativex'
depends 'pbis-nativex'
depends 'ntp'
depends 'motd'
depends 'chef-client'
