name             'role-nat-nativex'
maintainer       'NativeX'
maintainer_email 'adrian.herrera@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-nat-nativex'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'ohai-nativex'
depends 'aws'
depends 'vim'
depends 'nano'
depends 'bash-completion'
depends 'dstat'
depends 'numad-nativex'
depends 'tuned-nativex'
depends 'nfs'
depends 'ephemeral_lvm'
depends 'snmp'
depends 'dnsupdate-nativex::addprv'
depends 'hostname-nativex::updatehostname'
depends 'yum-nativex::customrepo'
depends 'spacewalk-nativex'
depends 'pbis-nativex'
depends 'yum-nativex::doupgrade'
depends 'yum-nativex::deleterepo'
depends 'ntp'
depends 'motd'
depends 'chef-client::delete_validation'
depends 'chef-client'