name             'role-apache-webserver-nativex'
maintainer       'NativeX'
maintainer_email 'adrian.herrera@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-apache-webserver-nativex'
version          '0.1.0'

depends 'role-base-nativex'
depends 'iptables-nativex'
depends 'apache2'