name             'role-createsession-nativex'
maintainer       'NativeX'
maintainer_email 'adrian.herrera@nativex.com'
license          'All rights reserved'
description      'Installs/Configures role-createsession-nativex'
version          '0.1.0'

depends 'role-base-nativex'
depends 'git'
depends 'blockdevice-nativex'
depends 'nodejs'
depends 'tuned-nativex'
depends 'maven'
