maintainer       "Randy Dickinson"
maintainer_email "rtd@i-x.net"
license          "Apache 2.0"
name             "likewise"
description      "Installs and configures Likewise Open"
version          "0.3.0"
supports         "debian"
supports         "ubuntu"
supports         "centos"
