name             'role-domain-controller-simplyadrian'
maintainer       'simplyadrian'
maintainer_email 'simplyadrian@gmail.com'
license          'All rights reserved'
description      'Installs/Configures role-domain-controller-simplyadrian'
version          '0.3.0'

depends 'ad-simplyadrian'
depends 'autopatch-simplyadrian'
depends 'aws'
depends 'timezone-simplyadrian'
depends 'chef-client'
depends 'chef-sugar'
depends 'windows'
